import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronDown,ChevronRight,Eye,EyeOff,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {assetUrl} from './base-url';
import {LINE_IDS,MODELS,listenParent,postToParent,readUrlRequest,type EmbedRequest,type ModelId} from './embed';
import {DEFAULT_VISIBLE,MORE_SYSTEMS,MVMT_REGIONS,NERVOUS_GROUP,ORGAN_SYSTEMS,PRIMARY_SYSTEMS,SYSTEMS,EXPLANATIONS,TRAILING_SYSTEMS,VESSEL_SYSTEMS,chunkKeysFor,contextKeysFor,explanation,regionBounds,type Atlas,type Concept,type FascialLine,type MuscleDepth,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
/** What is visible before any request: the URL's systems if it names them, else the defaults. Arteries, veins and
 * organs are never on by default, so the first fetch is the region (or the overview) alone. */
function initialVisible():SystemId[]{const req=readUrlRequest();return req.systems??DEFAULT_VISIBLE;}
const ORGAN_PRESET:SystemId[]=['cardiac','respiratory','digestive','urinary','endocrine','reproductive'];
/** The same debt mvmt-program carries: the nerves and the cord were authored from a written specification, not
 * imaging, and drawn beside geometry that was they would look equally authoritative. Shown whenever a schematic
 * layer is on or a schematic part is selected; not a tooltip, no close control. */
const SCHEMATIC='Schematic — indicative path only';
/** Myers argues the lines from dissection and reasoning; what the viewer can draw is the stations along the route,
 * because the connective tissue between them has no geometry here. Shown with every line, not dismissible. */
const LINE_CAVEAT='A model, not a dissected structure. What lights up is the stations along the route — the fascia running between them has no geometry here.';
/** Each line in a sentence, for the panel and for a patient: mvmt-program's copy, so the two viewers say the same thing. */
const LINE_BLURB:Record<string,string>={
 SBL:'From the sole of the foot to the brow, over the back of the body. Holds the body upright and prevents it folding forward.',
 SFL:'From the top of the foot to the side of the skull. Balances the back line and protects the soft front of the body.',
 LL:'From the outside of the foot up each side to the ear. Balances front against back and left against right, and brakes side-bending.',
 SPL:'Loops around the body in a double helix. Maintains rotational balance, and its imbalance shows as a twist through the trunk.',
 DFL:"The body's myofascial core, from the sole of the foot through the inner leg, pelvis and trunk to the jaw. The hardest to reach and the most implicated in persistent postural problems.",
 SFAL:'From the chest and back to the palm. The line of pulling toward you and gripping.',
 DFAL:'From the ribs through the biceps to the thumb. Controls the angle of the hand in space.',
 SBAL:'From the skull and spine over the shoulder to the back of the hand. The line of pushing away.',
 DBAL:'From the spine through the rotator cuff to the little-finger side of the hand. Stabilises the shoulder during arm work.',
 FFL:'From one shoulder across the front of the body to the opposite thigh. Loaded in throwing and any cross-body action.',
 BFL:'From one shoulder across the back to the opposite thigh. The other half of the throwing pattern.',
 IFL:'Down the same side, from the shoulder to the inner thigh. Loaded in same-side reaching and carrying.',
};
const SYSTEM_LABEL:Partial<Record<SystemId,string>>={nervous:'Brain & cranial nerves'};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(()=>({...initial,visible:initialVisible()})),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const [model,setModel]=useState<ModelId>(()=>readUrlRequest().model??'bp3d'),[patient,setPatient]=useState(()=>readUrlRequest().patient??false),[region,setRegion]=useState(()=>readUrlRequest().region??'');
 const [more,setMore]=useState(false),[nervesOpen,setNervesOpen]=useState(false),[depth,setDepth]=useState<MuscleDepth>(0),[lineOn,setLineOn]=useState(false),[lineId,setLineId]=useState<string|null>(null),[lines,setLines]=useState<FascialLine[]|null>(null),[frame,setFrame]=useState<{id:string;n:number}|null>(null);
 // The URL request is applied once the manifest is in; a message that arrives before then waits here too.
 const pending=useRef<EmbedRequest|null>(readUrlRequest());
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:initialVisible()});fetch(assetUrl(MODELS[model].manifest),{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[model]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 // the fascial lines are fetched the first time they are asked for
 useEffect(()=>{if(!lineOn||lines)return;const abort=new AbortController();fetch(assetUrl('/models/fascial-lines.json'),{signal:abort.signal}).then(r=>r.json()).then(d=>setLines(d.lines as FascialLine[])).catch(()=>{});return()=>abort.abort();},[lineOn,lines]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const concepts=useMemo(()=>new Map(atlas?.concepts.map(c=>[c.id,c])),[atlas]);
 // which chunk sets the scene holds: a region fetches its own BP3D and MVMT chunks, then its context; the whole body the overview
 const chunkKeys=useMemo(()=>atlas?chunkKeysFor(atlas,region||null,state.visible):[],[atlas,region,state.visible]);
 const contextKeys=useMemo(()=>atlas?contextKeysFor(atlas,region||null):[],[atlas,region]);
 const focus=useMemo(()=>atlas&&region?regionBounds(atlas,region):null,[atlas,region]);
 // patient view keeps the six landmarks the fit could not place within 10 mm off the screen
 // patient view keeps every part the fit could not place with confidence off the screen: the six landmarks over 10 mm, and any
 // carried-over part more than 20% of whose surface sits further than 6 mm from the BP3D body
 const hiddenParts=useMemo(()=>patient&&atlas?atlas.parts.filter(p=>p.fitConfidence==='low').map(p=>p.id):[],[atlas,patient]);
 // the picked line as the set of parts its stations resolve to, both sides; the scene lights these and ghosts the rest
 const line=useMemo(()=>{if(!lineOn||!lineId||!lines||!atlas)return null;const l=lines.find(x=>x.id===lineId);if(!l)return null;return {id:l.id,parts:[...new Set(l.stations.flatMap(st=>st.resolve.flatMap(r=>concepts.get(r.id)?.elements??[])))]};},[lineOn,lineId,lines,atlas,concepts]);
 // the chunks a region view holds at full detail, so a station row can say when its parts are in another region
 const loadedChunks=useMemo(()=>new Set(chunkKeys.filter(k=>k.startsWith('main:')).map(k=>+k.slice(5))),[chunkKeys]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const present=(id:SystemId)=>counts[id]>0;
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const regionInfo=atlas?.regions?.find(r=>r.id===region);
 const inRegion=(p:{region?:string;system:SystemId})=>!region||!regionInfo||p.region===region||!(p.region);
 const visibleCount=atlas?.parts.filter(p=>inRegion(p)&&!hiddenParts.includes(p.id)&&(state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id))).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{postToParent({type:'select',id:chosen?.id??null,name:chosen?.name??null});},[chosen]);
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const framePart=(id:string)=>{choosePart(id);setFrame(f=>({id,n:(f?.n??0)+1}));};
 const setVisible=(visible:SystemId[])=>{setDetails(false);setChosen(null);setState(s=>({...s,selected:[],isolate:false,visible}));};
 const toggle=(id:SystemId)=>setVisible(state.visible.includes(id)?state.visible.filter(x=>x!==id):[...state.visible,id]);
 const toggleGroup=(ids:SystemId[])=>{const on=ids.some(id=>state.visible.includes(id));setVisible(on?state.visible.filter(x=>!ids.includes(x)):[...new Set([...state.visible,...ids])]);};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);setDepth(0);setLineOn(false);setLineId(null);setFrame(null);};
 // a picked line survives a region change: in a region view it lights the stations the region holds and ghosts the region
 const pickRegion=(id:string)=>{setRegion(id);setDetails(false);setChosen(null);setState(s=>({...s,selected:[],isolate:false,explode:0,reset:s.reset+1,rotate:false}));};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const apply=(req:EmbedRequest)=>{
  if(req.model&&req.model!==model){pending.current={...(pending.current??{}),...req,model:undefined};setModel(req.model);return;}
  if(!atlas){pending.current={...(pending.current??{}),...req};return;}
  if(req.patient!==undefined)setPatient(req.patient);
  if(req.region!==undefined)pickRegion(MVMT_REGIONS.some(r=>r.id===req.region)?req.region:'');
  if(req.systems)setState(s=>({...s,visible:req.systems!,selected:[],isolate:false}));
  if(req.view)setState(s=>({...s,view:req.view!,reset:s.reset+1,rotate:false}));
  if(req.select){const id=req.select,part=parts.get(id),concept=atlas.concepts.find(c=>c.id===id)??(part?{id:part.conceptId,name:part.name,elements:[id]}:null);if(concept)choose(concept);else postToParent({type:'unresolved',id});}
  if(req.line!==undefined){if(!req.line){setLineOn(false);setLineId(null);}else if(LINE_IDS.includes(req.line)){setLineOn(true);setLineId(req.line);}else postToParent({type:'unresolved',line:req.line});}
 };
 const applyRef=useRef(apply);applyRef.current=apply;
 // The detail and about sheets render in a portal outside <main>, so the patient flag also goes on the root element.
 useEffect(()=>{document.documentElement.classList.toggle("patient",patient);},[patient]);
 useEffect(()=>{if(!atlas)return;postToParent({type:'ready',model,parts:atlas.parts.length});const req=pending.current;pending.current=null;if(req)applyRef.current(req);},[atlas]);
 useEffect(()=>listenParent(req=>applyRef.current(req)),[]);
 const nervesOn=NERVOUS_GROUP.some(id=>state.visible.includes(id));
 const schematicOn=state.visible.includes('central-nerves')||state.visible.includes('peripheral-nerves')||selectedParts.some(p=>p.source==='schematic');
 const lineData=lines?.find(l=>l.id===lineId);
 const systemRow=(id:SystemId,sub=false)=>{const s=SYSTEMS.find(x=>x.id===id)!;return <div className={`system-row ${state.visible.includes(id)?'enabled':''} ${sub?'sub-row':''}`} key={id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setVisible([id])}><span className="system-dot" style={{background:s.color}}/>{SYSTEM_LABEL[id]??s.name}<span className="system-count">{counts[id]}</span></Button><Switch checked={state.visible.includes(id)} onCheckedChange={()=>toggle(id)} aria-label={`Show ${s.name.toLowerCase()}`}/></div>;};
 const activeCount=[...PRIMARY_SYSTEMS,...NERVOUS_GROUP,...TRAILING_SYSTEMS,...MORE_SYSTEMS].filter(present).length;
 return <main className={`studio${patient?' patient':''}`} data-region={region||undefined}>
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,chunkKeys,contextKeys,hiddenParts,depth,frame,line,focus,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onFrame={framePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  {schematicOn&&<div className="schematic-label" role="note">{SCHEMATIC}</div>}
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> INTERACTIVE ANATOMY</div><h1>MVMT Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} modeled pieces <span>·</span> {MODELS[model].source}{patient&&<><span>·</span>Patient view</>}</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className={`icon-button ${patient?'active':''}`} aria-pressed={patient} title={patient?'Patient view is on: identifiers, counts and low-confidence landmarks are hidden':'Patient view: hide identifiers, counts and low-confidence landmarks so the screen can face a patient'} aria-label="Patient view" onClick={()=>setPatient(p=>!p)}>{patient?<EyeOff size={18}/>:<Eye size={18}/>}</Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Regions and systems">
   <div className="panel-heading"><span>Region</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close panel"><X size={18}/></Button></div>
   <div className="region-chips" role="radiogroup" aria-label="Region"><button type="button" className={`chip ${!region?'active':''}`} aria-pressed={!region} onClick={()=>pickRegion('')}>Whole body</button>{MVMT_REGIONS.map(r=><button type="button" key={r.id} className={`chip ${region===r.id?'active':''}`} aria-pressed={region===r.id} onClick={()=>pickRegion(r.id)}>{r.name}</button>)}</div>
   <div className="panel-heading"><span>Systems</span><Badge variant="secondary" className="desktop-only small-number">{activeCount}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={[...PRIMARY_SYSTEMS,...NERVOUS_GROUP,...TRAILING_SYSTEMS].filter(present).every(x=>state.visible.includes(x))} onClick={()=>setVisible([...PRIMARY_SYSTEMS,...NERVOUS_GROUP,...TRAILING_SYSTEMS].filter(present))}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setVisible(['skeletal'])}>Skeleton</Button><Button variant="ghost" aria-pressed={ORGAN_PRESET.every(id=>state.visible.includes(id))} onClick={()=>{setMore(true);setVisible(ORGAN_PRESET);}}>Organs</Button></div>
   <div className="system-list">
    {PRIMARY_SYSTEMS.filter(present).map(id=><div key={id}>{systemRow(id)}{id==='muscular'&&state.visible.includes('muscular')&&<div className="depth-seg" role="radiogroup" aria-label="Muscle depth">{([0,1,2] as MuscleDepth[]).map(d=><button type="button" key={d} aria-pressed={depth===d} onClick={()=>setDepth(d)}>{['All','Superficial','Deep'][d]}</button>)}</div>}</div>)}
    <div className={`system-row group-row ${nervesOn?'enabled':''}`}><Button variant="ghost" className="system-name" onClick={()=>setNervesOpen(o=>!o)} aria-expanded={nervesOpen} title="Central and peripheral nerves, and BodyParts3D's brain and cranial nerves"><span className="system-dot" style={{background:'#E0A427'}}/>Nervous system<span className="system-count">{NERVOUS_GROUP.reduce((n,id)=>n+counts[id],0)}</span>{nervesOpen?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</Button><Switch checked={nervesOn} onCheckedChange={()=>toggleGroup(NERVOUS_GROUP.filter(present))} aria-label="Show the nervous system"/></div>
    {nervesOpen&&NERVOUS_GROUP.filter(present).map(id=>systemRow(id,true))}
    {TRAILING_SYSTEMS.filter(present).map(id=>systemRow(id))}
    <div className={`system-row ${lineOn?'enabled':''}`}><Button variant="ghost" className="system-name" title="Trace a myofascial line: its stations lit in the line colour, the rest of the body a ghost" onClick={()=>setLineOn(o=>!o)}><span className="system-dot" style={{background:'var(--v3-line)'}}/>Fascial lines<span className="system-count">12</span></Button><Switch checked={lineOn} onCheckedChange={()=>setLineOn(o=>!o)} aria-label="Show fascial lines"/></div>
    {/* Every station is listed, and one the body cannot light says so on its row - nothing is dropped for tidiness. The
        station list is the one thing patient view hides here: the highlight and the blurb are what a patient is shown. */}
    {lineOn&&<div className="line-block">{lines?<div className="line-list">{lines.map(l=><button type="button" key={l.id} aria-pressed={lineId===l.id} title={l.name} onClick={()=>setLineId(id=>id===l.id?null:l.id)}>{l.id}</button>)}</div>:<p className="line-note">Loading the lines…</p>}{lineData?<div className="line-info"><strong>{lineData.name}</strong><p className="line-blurb">{LINE_BLURB[lineData.id]}</p><p className="line-caveat">{LINE_CAVEAT}</p><ol>{lineData.stations.map((st,i)=>{const ids=[...new Set(st.resolve.flatMap(r=>concepts.get(r.id)?.elements??[]))];const here=!region||ids.some(id=>{const p=parts.get(id);return !!p&&loadedChunks.has(p.chunk);});const note=st.status==='none'?'not on this model':st.status==='attachments'?'attachments only · muscle not on this model':!here?'not in this region':'';return <li key={st.structure+i}><button type="button" onClick={()=>{if(ids.length)choose({id:st.structure,name:st.name,elements:ids});}}>{st.name}</button>{note&&<span className="line-missing">{note}</span>}</li>;})}</ol>{state.explode>0&&<p className="line-note">Hidden while the anatomy is exploded.</p>}{state.isolate&&<p className="line-note">Hidden while a structure is isolated.</p>}</div>:<p className="line-note">Pick a line to trace it through the body.</p>}</div>}
    <button type="button" className="fold-toggle" aria-expanded={more} onClick={()=>setMore(o=>!o)}>{more?<ChevronDown size={14}/>:<ChevronRight size={14}/>}More systems<span className="system-count">{MORE_SYSTEMS.filter(present).length}</span></button>
    {more&&MORE_SYSTEMS.filter(present).map(id=>systemRow(id))}
   </div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setVisible([])}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, ACL, ASIS…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','back','side','right','top'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={['Three-quarter','Anterior','Posterior','Left','Right','Superior'][i]+' view'} aria-label={['Three-quarter','Anterior','Posterior','Left','Right','Superior'][i]+' view'}><span>{['¾','A','P','L','R','S'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':region?(MVMT_REGIONS.find(r=>r.id===region)?.name.toUpperCase()+' · NEIGHBOURS DIMMED'):'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect <b>·</b> Double-tap to frame</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · {region?MVMT_REGIONS.find(r=>r.id===region)?.name:'Whole body'}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMY'}{selected?.region&&<span className="eyebrow-region"> · {MVMT_REGIONS.find(r=>r.id===selected.region)?.name}</span>}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle>{selectedParts.some(p=>p.source==='schematic')&&<div className="schematic-inline">{SCHEMATIC}</div>}{selected?.fitConfidence==='low'&&<div className="confidence-note">{selected.system==='landmarks'?`Fit confidence low: this landmark's rule landed ${Math.round((selected.fitResidual??0)*1000)} mm from where the fit expected it on this body.`:`Fit confidence low: ${Math.round(((selected as {fitFarFraction?:number}).fitFarFraction??0)*100)}% of this part sits more than 6 mm from the BodyParts3D surface.`}</div>}</div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href={selected?.source?'https://github.com/calvinyu94-debug/mvmt-anatomy':'https://lifesciencedb.jp/bp3d/'} target="_blank" rel="noreferrer">{selected?.source==='schematic'?'Authored in mvmt-anatomy':selected?.source==='zanatomy'?'From Z-Anatomy, fitted onto this body':'View anatomical source'} <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{if(selected)framePart(selected.id);}}>Frame</Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setChosen(null);setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A body, revealed.</SheetTitle><SheetDescription>The adult male reference anatomy from BodyParts3D, with MVMT's layers fitted onto it.</SheetDescription><div className="about-copy"><p><strong>Male · BodyParts3D</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.</p><p><strong>MVMT layers</strong><br/>Fascia, joints & ligaments, insertions and landmarks from the Z-Anatomy atlas, fitted onto this body by landmark rules; the nerves and the spinal cord are schematic and say so.</p><p>This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once. Colors and system groupings are designed for exploration. The geometry is simplified for the web. This is an anatomical reference, not a diagnostic or surgical tool.</p><h3>Source</h3><p>BodyParts3D, © The Database Center for Life Science, CC Attribution 4.0 International. Z-Anatomy, CC BY-SA 4.0. Human Atlas, MIT.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://github.com/calvinyu94-debug/mvmt-anatomy" target="_blank" rel="noreferrer">MVMT layers and the fit <ArrowUpRight size={14}/></a><a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">Human Atlas <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
